FROM postgres:14-alpine
FROM node:17-alpine3.12
FROM maven:3.8.7-eclipse-temurin-19 as maven
WORKDIR front-end
ENV PATH ./front-end/node_modules/.bin:$PATH
COPY ./front-end/package.json .
COPY ./front-end .
RUN npm install -g
EXPOSE 3000

WORKDIR db
ENV SPRING_PROFILES_ACTIVE=default
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
ENV POSTGRES_PASSWORD=asd123
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres
# Expose port 5432
EXPOSE 5432




WORKDIR /back-end
COPY ./back-end/mvnw .
COPY ./back-end/.mvn .mvn
COPY ./back-end/pom.xml .
COPY ./back-end/src src
COPY ./back-end/apache-maven-3.9.6 .
#COPY --from=build-node ./src/main/resources ./src/main/resources

ENV M3_HOME=./apache-maven-3.9.6
RUN mvn clean install  -DskipTests


COPY ./back-end/target/*.jar app.jar
EXPOSE 8080
CMD ["postgres"]

CMD ["java","-Dspring.profiles.active=dev","-jar","app.jar"]
CMD ["npm", "start"]
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","app.jar"]



