DROP TABLE IF EXISTS tag_rel;

DROP TABLE IF EXISTS articles;

DROP TABLE IF EXISTS images;

DROP TABLE IF EXISTS tags;

CREATE TABLE "articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fname" varchar(100) UNIQUE NOT NULL,
  "image_id" integer
);

CREATE TABLE "images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fname" varchar(100) NOT NULL
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caption" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "tag_rel" (
  "tag_id" integer NOT NULL,
  "article_id" integer NOT NULL
);

ALTER TABLE
  "articles"
ADD
  FOREIGN KEY ("image_id") REFERENCES "images" ("id");

ALTER TABLE
  "tag_rel"
ADD
  FOREIGN KEY ("article_id") REFERENCES "articles" ("id");

ALTER TABLE
  "tag_rel"
ADD
  FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");