DROP TABLE IF EXISTS tag_rel CASCADE;

DROP TABLE IF EXISTS user_tag_rel CASCADE;

DROP TABLE IF EXISTS articles CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS images CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP TABLE IF EXISTS deadlines CASCADE;

CREATE TABLE "articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fname" varchar(100) UNIQUE NOT NULL,
  "image_id" integer
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "password" varchar(100) NOT NULL,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "role" varchar(100) NOT NULL
);

CREATE TABLE "images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fname" varchar(100) NOT NULL
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caption" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "tag_rel" (
  "tag_id" integer NOT NULL,
  "article_id" integer NOT NULL
);

CREATE TABLE "user_tag_rel" (
  "tag_id" integer NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE "deadlines"(
    "id" integer BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL,
    "date" timestamp NOT NULL
    "information" varchar(1000) NOT NULL
);

ALTER TABLE
  "articles"
ADD
  FOREIGN KEY ("image_id") REFERENCES "images" ("id");

ALTER TABLE
  "tag_rel"
ADD
  FOREIGN KEY ("article_id") REFERENCES "articles" ("id");

ALTER TABLE
  "tag_rel"
ADD
  FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE
  "user_tag_rel"
ADD
  FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE
  "user_tag_rel"
ADD
  FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");